<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework Condition="$(BazelFetch) == 'true'">net8.0</TargetFramework>
    <TargetFramework Condition="$(BazelFetch) == ''">net8.0</TargetFramework>
    <RootNamespace>NuGetParser</RootNamespace>
  </PropertyGroup>

</Project>
